Fix test errors in Loader_test.php and URI_test.php
Change exceptions from Exception to RuntimeException since PHPUnit 3.6
doesn't like you to expect generic exceptions. The error it gives is:

InvalidArgumentException: You must not expect the generic exception class
travis-ci.org/#!/tiyowan/CodeIgniter/builds/832518

This issue addressed by using exceptions that are more specific.